// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "1.2.1"
    static let gitHash = "d6c0c83"
    static let gitDate = "2026-08-23 12:10:59 +0200"
    static let gitMessage = "Shorten the path from Download to first working session (#89)"
    static let buildDate = "2026-08-23 12:20"
}
