// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "0.9.0"
    static let gitHash = "66d4af2"
    static let gitDate = "2026-04-13 12:38:51 +0200"
    static let gitMessage = "chore: bump version to 0.9.0"
    static let buildDate = "2026-04-13 12:44"
}
