// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "0.1.0"
    static let gitHash = "ed0a29f"
    static let gitDate = "2026-04-06 17:41:12 +0200"
    static let gitMessage = "Merge branch 'sort-tabs'"
    static let buildDate = "2026-04-06 18:10"
}
