#!/bin/bash
# Builds Canopy.app via Xcode and installs it to /Applications.

set -euo pipefail

cd "$(dirname "$0")/.."

APP_NAME="Canopy"
SCHEME="Canopy"
PROJECT="Canopy.xcodeproj"
DERIVED_DATA="build/DerivedData"
ARCHIVE="build/${APP_NAME}.xcarchive"

# Generate build info from git
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_DATE=$(git log -1 --format=%ci 2>/dev/null || echo "unknown")
GIT_MSG=$(git log -1 --format=%s 2>/dev/null || echo "unknown")
BUILD_DATE=$(date "+%Y-%m-%d %H:%M")

cat > Canopy/App/BuildInfo.swift << BUILDINFO
// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "0.1.0"
    static let gitHash = "${GIT_HASH}"
    static let gitDate = "${GIT_DATE}"
    static let gitMessage = "${GIT_MSG}"
    static let buildDate = "${BUILD_DATE}"
}
BUILDINFO

echo "Building with Xcode (Release)..."
xcodebuild \
    -project "$PROJECT" \
    -scheme "$SCHEME" \
    -configuration Release \
    -derivedDataPath "$DERIVED_DATA" \
    -archivePath "$ARCHIVE" \
    archive \
    | xcpretty 2>/dev/null || cat

APP_PATH="${ARCHIVE}/Products/Applications/${APP_NAME}.app"

echo "Installing to /Applications..."
rm -rf "/Applications/${APP_NAME}.app"
cp -r "$APP_PATH" "/Applications/${APP_NAME}.app"

echo "Done! Installed at: /Applications/${APP_NAME}.app"
