#!/bin/bash
# Creates a proper macOS .app bundle from the swift build output.
#
# Why? A raw executable doesn't get proper window server access on macOS.
# The .app bundle tells macOS "this is a GUI application" via its Info.plist,
# which enables proper window rendering, dock icon, menu bar, etc.

set -euo pipefail

APP_NAME="Canopy"
BUNDLE_ID="com.canopy.app"
BUILD_DIR=".build/release"
APP_DIR="build/${APP_NAME}.app"

# Generate build info from git
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_DATE=$(git log -1 --format=%ci 2>/dev/null || echo "unknown")
GIT_MSG=$(git log -1 --format=%s 2>/dev/null || echo "unknown")
BUILD_DATE=$(date "+%Y-%m-%d %H:%M")

cat > Canopy/App/BuildInfo.swift << BUILDINFO
// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "0.1.0"
    static let gitHash = "${GIT_HASH}"
    static let gitDate = "${GIT_DATE}"
    static let gitMessage = "${GIT_MSG}"
    static let buildDate = "${BUILD_DATE}"
}
BUILDINFO

echo "Building release..."
swift build -c release 2>&1

echo "Creating app bundle..."
rm -rf "$APP_DIR"
mkdir -p "${APP_DIR}/Contents/MacOS"
mkdir -p "${APP_DIR}/Contents/Resources"

# Copy the binary
cp "${BUILD_DIR}/${APP_NAME}" "${APP_DIR}/Contents/MacOS/${APP_NAME}"

# Copy the icon
cp "Resources/Canopy.icns" "${APP_DIR}/Contents/Resources/Canopy.icns" 2>/dev/null || true

# Create Info.plist — this tells macOS this is a real GUI app
cat > "${APP_DIR}/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>${APP_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>CFBundleIconFile</key>
    <string>Canopy</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.developer-tools</string>
    <key>NSSupportsAutomaticTermination</key>
    <false/>
    <key>NSSupportsSuddenTermination</key>
    <false/>
</dict>
</plist>
PLIST

echo "Done! App bundle at: ${APP_DIR}"
echo "Run with: open ${APP_DIR}"
