#!/bin/bash
# Builds Canopy.app via Xcode and installs it to /Applications.

set -euo pipefail

cd "$(dirname "$0")/.."

RELEASE_MODE=0
DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        # Keep the regenerated BuildInfo.swift in the working tree. Use this
        # when cutting a release, where the committed file is *meant* to change.
        --release) RELEASE_MODE=1 ;;
        # Stop after generating BuildInfo.swift. Exists so the restore
        # guarantee can be tested without a multi-minute archive.
        --dry-run) DRY_RUN=1 ;;
        *) echo "ERROR: unknown argument: $arg" >&2; exit 1 ;;
    esac
done

if [[ ! -f VERSION ]]; then
    echo "ERROR: VERSION file not found." >&2
    exit 1
fi
VERSION_STR=$(tr -d '[:space:]' < VERSION)
if [[ -z "$VERSION_STR" ]]; then
    echo "ERROR: VERSION file is empty." >&2
    exit 1
fi

APP_NAME="Canopy"
SCHEME="Canopy"
PROJECT="Canopy.xcodeproj"
DERIVED_DATA="build/DerivedData"
ARCHIVE="build/${APP_NAME}.xcarchive"

# Generate build info from git
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_DATE=$(git log -1 --format=%ci 2>/dev/null || echo "unknown")
GIT_MSG=$(git log -1 --format=%s 2>/dev/null | sed 's/"/\\"/g' || echo "unknown")
BUILD_DATE=$(date "+%Y-%m-%d %H:%M")

BUILDINFO_PATH="Canopy/App/BuildInfo.swift"

# BuildInfo.swift is tracked and load-bearing: .github/workflows/release.yml
# validates the *committed* copy against VERSION, and AboutView/UpdateChecker
# read it at runtime. But CLAUDE.md tells contributors to run this script after
# every change, so regenerating it unconditionally leaves a dirty tree on every
# build, which `git add -A` then sweeps into unrelated commits -- it put a stale
# hash into PR #50 and had to be reverted. Build from the fresh values, then put
# the committed copy back, unless this is an intentional release build.
if [[ "$RELEASE_MODE" -eq 0 && -f "$BUILDINFO_PATH" ]]; then
    BUILDINFO_BACKUP=$(mktemp)
    cp "$BUILDINFO_PATH" "$BUILDINFO_BACKUP"
    trap 'cp "$BUILDINFO_BACKUP" "$BUILDINFO_PATH"; rm -f "$BUILDINFO_BACKUP"' EXIT
fi

cat > "$BUILDINFO_PATH" << BUILDINFO
// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "${VERSION_STR}"
    static let gitHash = "${GIT_HASH}"
    static let gitDate = "${GIT_DATE}"
    static let gitMessage = "${GIT_MSG}"
    static let buildDate = "${BUILD_DATE}"
}
BUILDINFO

if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "Dry run: BuildInfo.swift generated, skipping archive and install."
    exit 0
fi

echo "Building with Xcode (Release)..."
# Preserve the archive command's exit status across the pipe. Without
# pipefail-aware checking, a failed `xcodebuild archive` whose output went
# through `xcpretty` would silently fall through and we'd install a stale
# .xcarchive from a previous run.
set -o pipefail
if command -v xcpretty >/dev/null 2>&1; then
    xcodebuild \
        -project "$PROJECT" \
        -scheme "$SCHEME" \
        -configuration Release \
        -derivedDataPath "$DERIVED_DATA" \
        -archivePath "$ARCHIVE" \
        -skipPackagePluginValidation \
        MARKETING_VERSION="${VERSION_STR}" \
        archive \
        | xcpretty
else
    xcodebuild \
        -project "$PROJECT" \
        -scheme "$SCHEME" \
        -configuration Release \
        -derivedDataPath "$DERIVED_DATA" \
        -archivePath "$ARCHIVE" \
        -skipPackagePluginValidation \
        MARKETING_VERSION="${VERSION_STR}" \
        archive
fi

APP_PATH="${ARCHIVE}/Products/Applications/${APP_NAME}.app"

if [[ ! -d "$APP_PATH" ]]; then
    echo "ERROR: archive did not produce ${APP_PATH}; refusing to install a stale build." >&2
    exit 1
fi

echo "Installing to /Applications..."
rm -rf "/Applications/${APP_NAME}.app"
cp -r "$APP_PATH" "/Applications/${APP_NAME}.app"

echo "Done! Installed at: /Applications/${APP_NAME}.app"
